URLShortner/Models/CustomURL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace URLShortner.Models
{
    public class CustomURL
    {
        public string FullUrl { get; set; }
        public string shortUrl { get; set; }
    }
}

URLShortner/Models/bitly.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Xml;

namespace URLShortner.Models
{
    public class bitly
    {

        private string loginAccount;
        private string apiKeyForAccount;
        private string submitPath = @"http://api.bit.ly/shorten?version=2.0.1&format=xml";
        private int errorStatus = 0;
        private string errorMessage = "";


        /// <summary>
        /// Default constructor which will login with demo credentials
        /// </summary>
        /// <returns>A bitly class object</returns>
        public bitly()
            : this("o_mofttooh8", "R_d59bfb41308d4819a77be9151b929ce3")
        {

        }


        /// <summary>
        /// Overloaded constructor that takes a bit.ly login and apikey (if applicable)
        /// </summary>
        /// <returns>A bitly class object</returns>
        public bitly(string login, string APIKey)
        {
            loginAccount = login;
            apiKeyForAccount = APIKey;

            submitPath += "&login=" + loginAccount + "&apiKey=" + apiKeyForAccount;
        }


        // Properties to retrieve error information.
        public int ErrorCode
        {
            get { return errorStatus; }
        }

        public string ErrorMessage
        {
            get { return errorMessage; }
        }


        /// <summary>
        /// Shortens a provided URL
        /// </summary>
        /// <param name="url">A URL</param>
        /// <returns>A shortened bit.ly URL String</returns>
        public string shorten(string url)
        {
            errorStatus = 0;
            errorMessage = "";

            XmlDocument doc = buildDocument(url);

            if (doc.DocumentElement != null)
            {
                XmlNode shortenedNode = doc.DocumentElement.SelectSingleNode("results/nodeKeyVal/shortUrl");

                if (shortenedNode != null)
                {
                    return shortenedNode.InnerText;
                }
                else
                {
                    errorCode(doc);
                }
            }
            else
            {
                this.errorStatus = -1;
                this.errorMessage = "Unable to connect to bit.ly for shortening of URL";
            }

            return "";

        }


        // Sets error code and message in the situation we receive a response, but there was
        // something wrong with our submission.
        private void errorCode(XmlDocument doc)
        {
            XmlNode errorNode = doc.DocumentElement.SelectSingleNode("errorCode");
            XmlNode errorMessage = doc.DocumentElement.SelectSingleNode("errorMessage");

            if (errorNode != null)
            {
                this.errorStatus = Convert.ToInt32(errorNode.InnerText);
                this.errorMessage = errorMessage.InnerText;
            }
        }


        // Builds an XmlDocument using the XML returned by bit.ly in response 
        // to our URL being submitted
        private XmlDocument buildDocument(string url)
        {
            XmlDocument doc = new XmlDocument();

            try
            {
                // Load the XML response into an XML Document and return it.
                doc.LoadXml(readSource(submitPath + "&longUrl=" + url));
                return doc;
            }
            catch (Exception e)
            {
                return new XmlDocument();
            }
        }


        // Fetches a result from bit.ly provided the URL submitted
        private string readSource(string url)
        {
            WebClient client = new WebClient();

            try
            {
                using (StreamReader reader = new StreamReader(client.OpenRead(url)))
                {
                    // Read all of the response
                    return reader.ReadToEnd();
                    reader.Close();
                }
            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }
}

URLShortner/Controllers/URLShortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using URLShortner.Models;

namespace URLShortner.Controllers
{
    public class URLShortController : Controller
    {
        bitly b = new bitly();
        // GET: URLShort
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(CustomURL Urls)
        {
            Urls.FullUrl = Urls.FullUrl;
            Urls.shortUrl = b.shorten(Urls.FullUrl);
            return View(Urls);
        }
        public ActionResult Test()
        {
            return View();
        }
    }
}

URLShortner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

URLShortner/Views/URLShort/Index.cshtml
@model URLShortner.Models.CustomURL
@{
    Layout = null;
}

<!DOCTYPE html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link href="~/Content/css/cover.css" rel="stylesheet" />
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container">

        <div class="panel-group" style="margin-top:50px;">
            @using (Html.BeginForm("Index", "URLShort", FormMethod.Post, new { enctype = "multipart/form-data", id = "MainForm" }))
            {

                <div class="panel panel-default">
                    <div class="panel-heading">URL Shortening</div>
                    <div class="panel-body">
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.FullUrl, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                        </div>
                        <div class="col-md-4">
                            <input type="submit" name="btnSubmit" id="btnSubmit" value="Submit" class="btn btn-primary" />
                        </div>
                    </div>
                </div>

                if (Model != null)
                {
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3">Input long URL is</div>
                            <div class="col-md-9">
                                <a href="@Model.FullUrl" target="_blank">@Model.FullUrl</a>
                            </div>
                        </div>
                        <div class="col-xs-12"><hr></div>
                        <div class="row">
                            <div class="col-md-3"> Output Shortening URL is</div>
                            <div class="col-md-9">
                                <a href="@Model.shortUrl" target="_blank">@Model.shortUrl</a>
                            </div>
                        </div>
                    </div>
                </div>
                    }
                }
        </div>
    </div>
       
</body>
</html>

URLShortner/Views/URLShort/Test.cshtml
@model URLShortner.Models.CustomURL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>CustomURL</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FullUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullUrl, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.shortUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.shortUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.shortUrl, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>